version: "3.8"
services:
  ldap:
    image: edtasixm06/ldap22:latest
    container_name: ldap.edt.org
    hostname: ldap.edt.org
    ports: 
      - "389:389"
      - "636:636"
    networks:
     - 2hisx
  ssh:
    image: edtasixm06/ssh22:base
    container_name: ssh.edt.org
    hostname: ssh.edt.org
    ports:
      - "2022:22"
    networks:
     - 2hisx
networks:
  2hisx:
